/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_PWM.h"
#include "IN1_A_aliases.h"
#include "IN1_A.h"
#include "IN2_A_aliases.h"
#include "IN2_A.h"
#include "ENCD_B_2_aliases.h"
#include "ENCD_B_2.h"
#include "CONTROL_ENABLE_0.h"
#include "EN_B_aliases.h"
#include "EN_B.h"
#include "EN_A_aliases.h"
#include "EN_A.h"
#include "PWM_1.h"
#include "ENCD_B_1_aliases.h"
#include "ENCD_B_1.h"
#include "IN1_B_aliases.h"
#include "IN1_B.h"
#include "IN2_B_aliases.h"
#include "IN2_B.h"
#include "PWM_2.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "Timer_1.h"
#include "QuadDec_M2.h"
#include "QuadDec_M2_PVT.h"
#include "Clock_QENC.h"
#include "ENCD_A_2_aliases.h"
#include "ENCD_A_2.h"
#include "timer_1_isr.h"
#include "ENCD_A_1_aliases.h"
#include "ENCD_A_1.h"
#include "QuadDec_M1.h"
#include "QuadDec_M1_PVT.h"
#include "CONTROL_DISABLE_2.h"
#include "D2_B_aliases.h"
#include "D2_B.h"
#include "D2_A_aliases.h"
#include "D2_A.h"
#include "CONTROL_DISABLE_1.h"
#include "D1_B_aliases.h"
#include "D1_B.h"
#include "D1_A_aliases.h"
#include "D1_A.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "QuadDec_M2_isr.h"
#include "QuadDec_M2_Cnt16.h"
#include "QuadDec_M1_isr.h"
#include "QuadDec_M1_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

